version: '3.6'
services:
  lunieapi:
    image: lunieapi:latest
    container_name: lunieapi
    restart: "no"
    networks:
       - general
    ports:
      - "4000:4000"
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "lunieapi"
    restart: "no"
    container_name: caddy
    networks:
       - general
    ports:
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  caddy_certs:
networks:
  general:
