version: '3.6'
services:
  lunieapi:
    image: lunieapi:latest
  caddy:
    image: abiosoft/caddy:0.11.0
    depends_on:
    - "lunieapi"
    restart: always
    ports:
    - "443:443"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    - caddy_certs:/root/.caddy
volumes:
  caddy_certs:
