name: CI Test

on:
  push:
    branches:
      - test

jobs:
  test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: npm install
      run: npm install
    - name: Build image
      run: docker build -t dockerimage . && docker save | gzip > dockerimage.tgz
