name: Update existing droplet in Digital Ocean

on:
  push:
    branches:
      - update
jobs:
  test:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        version: 10
    - name: npm install
      run: npm install
    - name: Build image
      run: docker build -t lunieapi . 
    - name: Save file
      run: docker save lunieapi | gzip > lunieapi.tgz
    - name: prepare to push to Digital Ocean
      run: mkdir -p ~/.ssh && echo "${{ secrets.DO_PRIVATE_KEY }}"  | tr -d '\r' > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa && eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa && ssh-keyscan -H 157.245.121.175 >> ~/.ssh/known_hosts
    - name: push to Digital Ocean
      run:  rsync -4 lunieapi.tgz root@157.245.121.175:~/ && rsync -4 docker-compose.yml root@157.245.121.175:~/ && rsync -4 Caddyfile root@157.245.121.175:~/
    - name: Installing Docker Compose
      run: ssh root@157.245.121.175 "sudo curl -L \"https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)\" -o /usr/local/bin/docker-compose; sudo chmod +x /usr/local/bin/docker-compose"
    - name: Run on Digital Ocean
      run: ssh root@157.245.121.175 "docker image prune -a -f; docker load < lunieapi.tgz; docker container stop lunieapi;docker container stop caddy; docker container prune -f; docker-compose up --build"
